#! /bin/bash
#
# Entrypoint for the svnserver container:
#
#  - exports the ssh keys generated by the image to the shared /ssh-keys volume,
#  - starts a background sshd process on port 22,
#  - tails the sshd log file to keep container alive.

echo "-- Exporting ssh keys to ssh-keys volume."
rm -f /ssh-keys/id*
cp -pf /tmp/ssh-keys/* /ssh-keys/

echo "-- Starting container-only sshd in the background"
/usr/sbin/sshd -e -E /var/log/syslog -p 22

echo "-- Tailing sshd log"
tail -f /var/log/syslog

