version:  '3'

services:
  svnserver:
    build: ./01-svnserver
    volumes:
      - ./ssh-keys:/ssh-keys

  gitserver:
    build: ./02-gitserver
    volumes:
      - ./ssh-keys:/ssh-keys
      - ./configs:/configs
    depends_on:
      - svnserver
