#! /bin/bash

echo         "====================================="
echo -e "\e[1m== Subgit Configuration Experiment ==\e[0m"
echo         "====================================="
echo ""
echo "Start by verifying you can ssh to the svn container:"
echo -e "\e[90mNote: SSH Keys are: \e[1m$(cat /ssh-keys/key-type)\e[0m"
echo ""
echo -e " \$ \e[33mssh -i ~/.ssh/id-blank svnuser@svnserver\e[0m"
echo -e " \$ \e[33mssh -i ~/.ssh/id-keyed svnuser@svnserver\e[0m  (keyphrase is 'keyed')"
echo ""
echo "Then run:"
echo -e " \$ \e[33msubgit configure svn+ssh://svnserver/svn/Project1 Project1.git\e[0m"
echo ""

TEST_CONFIG="subgit-test-config"
if [ -f "/ssh-keys/${TEST_CONFIG}" -a ! -f "${TEST_CONFIG}" ]; then
  cp /ssh-keys/${TEST_CONFIG} ~/"${TEST_CONFIG}"
fi
if [ -f ~/"${TEST_CONFIG}" ]; then
  echo -e "See \e[33m~/${TEST_CONFIG}\e[0m for an example config to use after configure"
fi
echo -e "See \e[33mhistory\e[0m for a complete command run."
echo ""
